service: ${self:custom.appName}

provider:
  name: aws
  region: ${opt:region}
  stage: ${opt:stage}
  profile: ${opt:profile}
  deploymentBucket: ${self:custom.appNameFull}-deploys

plugins:
  - serverless-s3-sync
custom:
  appName: serverless-frontend
  appNameFull: serverless-frontend-${self:provider.stage}
  s3Sync:
    - bucketName: ${self:custom.appNameFull}
      localDir: build

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.appNameFull}
        WebsiteConfiguration:
          IndexDocument: index.html