service: ${self:custom.appName.${self:provider.stage}}

provider:
  name: ${opt:providerName, 'aws'}
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket: ${self:custom.appName.${self:provider.stage}}-deploys

plugins:
  - serverless-s3-sync
custom:
  appName: 
    dev: serverless-frontend-dev
    hml: serverless-frontend-hml
    prd: serverless-frontend-prd
  s3Sync:
    - bucketName: ${self:custom.appName.${self:provider.stage}}
      localDir: build

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.appName.${self:provider.stage}}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]